# Generated by Django 2.1 on 2020-05-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('subreddit', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=100)),
                ('upvotes', models.IntegerField()),
                ('sentiment', models.FloatField()),
            ],
        ),
    ]
